CREATE TABLE IF NOT EXISTS People
(ID INT PRIMARY KEY NOT NULL, 
FIRST VARCHAR(15) NOT NULL, 
MIDDLE VARCHAR(15),
LAST VARCHAR(15),
ALIAS VARCHAR (15),
AGE INT, 
SEX CHAR CHECK(SEX = 'Y' OR SEX = 'M'),
ADDRESS VARCHAR(50), 
STATE CHAR(2), 
MULTIPLIER INT,
SCORE INT,
PHONE VARCHAR(15),
EMAIL VARCHAR(30),
INTERESTS TEXT);

